logging.level: info
logging.to_files: false

#------------------------------ Log input --------------------------------
filebeat.inputs:
 - type: log
   enabled: true
   paths:
     - '/var/lib/docker/containers/logs/*.log'
   json.keys_under_root: true

   processors:
     - decode_json_fields:
         fields: ['message']
         target: json

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: changeme

#============================== Dashboards =====================================
#setup.dashboards:
#  enabled: true
#setup.kibana:
#  host: "kibana:80"
#  username: elastic
#  password: changeme