apiVersion: v1
data:
  example.property: hello
  example.property2: world
  someValue: "23"
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-15T17:14:34Z"
  name: special-config
  namespace: default
  resourceVersion: "23921"
  selfLink: /api/v1/namespaces/default/configmaps/special-config
  uid: ad45bbab-ac83-4731-bc07-4a163c9f3586
