apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: fiunchinho/codely-docker:latest
    name: hello-world
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      # I want to mount the config-volume defined below, on the path /tmp
      - name: secret-volume
        mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      configMap:
        # Provide the name of the Secret
        name: test-secret
  restartPolicy: Never
status: {}
