apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
    #Define the environment variables
  spec:
    containers:
    - image: fiunchinho/codely-docker:latest
      name: hello-world
      ports:
      - containerPort: 80
      resources: {}
    env:
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
          # The Secret containing the value you want to assign to the $SOME_VARIABLE env var
          name: test-secret
          # Specify the key associated with the value
          key: username
    - name: PASSWORD
      valueFrom: 
        secretKeyRef:
          # The Secret containing the value you want to assign to the $SOME_VARIABLE env var
          name: test-secret
          # Specify the key associated with the value
          key: password
    - name: ERROR_REPORTING
      valueFrom: 
        configMapKeyRef:
          # The ConfigMap containing the value you want to assign to the $SOME_VARIABLE env var
          name: special-config
          # Specify the key associated with the value
          key: someValue
  restartPolicy: Never
status: {}
